### ISSUE TITLE
Host service keeps running when app is in background

### ISSUE THREAD

**Issue by scorple** [semaphore-soft/Cypher#11]
~"Trying to connect <1>"

**Comment by bagelhobbit** [comment]
Code in the thread responsible for reconnection keeps a handle on the service, keeping it running while the app is in the background.

**Comment by bagelhobbit** [comment]
The AR activities do not unregister the BroadcastReceivers. This is how the user is alerted that the thread/service are still running in the background.

**Comment by bagelhobbit** [comment]
Reconnect will no longer occur in the background
